<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('product-list', [ProductController::class, 'listProduct'])->name('productList');
Route::get('product-detail', [ProductController::class, 'detailProduct'])->name('productDetail');
Route::post('product-filter', [ProductController::class, 'filterProduct'])->name('productFilter');


/*/**
 * GENERATED BY BREEZE FOR AUTH 
 */ 

Route::get('/dashboard', function () {                      //'middleware' is used to filter the HTTP request
    return view('dashboard');                               
})->middleware(['auth', 'verified'])->name('dashboard');    //'auth' checked if someone is connected and 'verified' check if its someone with verified email.

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::middleware(['auth', 'admin'])->group(function () {
    Route::get('/admin/panel', [ProductController::class, 'edit'])->name('adminPanel');
//     // Route::get('/admin', [ProductController::class, 'update'])->name('adminUpdate');
//     // Route::get('/admin', [ProductController::class, 'destroy'])->name('adminDestroy');
});


require __DIR__.'/auth.php';